name: emyu_telegram_bot
description: A dart wrapper for communicating with the telegram bot REST API.
version: 0.0.2
repository: https://github.com/emyu10/emyu_telegram_bot

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  collection: ^1.17.0
