part of '../types.dart';

class Message {
  final int messageId;
  User? from;
  Chat? senderChat;
  final int date;
  final Chat chat;
  User? forwardFrom;
  Chat? forwardFromChat;
  int? forwardFromMessageId;
  String? forwardSignature;
  String? forwardSenderName;
  int? forwardDate;
  bool? isAutomaticForward;
  Message? replyToMessage;
  User? viaBot;
  int? editDate;
  bool? hasProtectedContent;
  String? mediaGroupId;
  String? authorSignature;
  String? text;
  List<MessageEntity>? entities;
  Animation? animation;
  Audio? audio;
  Document? document;
  List<PhotoSize>? photo;
  Sticker? sticker;
  Video? video;
  VideoNote? videoNote;
  Voice? voice;
  String? caption;
  List<MessageEntity>? captionEntities;
  Contact? contact;
  Dice? dice;
  Game? game;
  Poll? poll;
  Venue? venue;
  Location? location;
  List<User>? newChatMembers;
  User? leftChatMember;
  String? newChatTitle;
  PhotoSize? newChatPhoto;
  bool? deleteChatPhoto;
  bool? groupChatCreated;
  bool? superGroupChatCreated;
  bool? channelChatCreated;
  MessageAutoDeleteTimerChanged? messageAutoDeleteTimerChanged;
  int? migrateToChatId;
  int? migrateFromChatId;
  Message? pinnedMessage;
  Invoice? invoice;
  SuccessfulPayment? successfulPayment;
  String? connectedWebsite;
  PassportData? passportData;
  ProximityAlertTriggered? proximityAlertTriggered;
  VideoChatScheduled? videoChatScheduled;
  VideoChatStarted? videoChatStarted;
  VideoChatEnded? videoChatEnded;
  VideoChatParticipantsInvited? videoChatParticipantsInvited;
  WebAppData? webAppData;
  InlineKeyboardMarkup? replyMarkup;

  Message({required this.messageId, required this.date, required this.chat});
}
